version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: node dist/server.js
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    command: node dist/indexer.js
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      api:
        condition: service_healthy

networks:
  app-network:
    driver: bridge